### ISSUE TITLE
Database tables does not created during setup.

### ISSUE THREAD

**Issue by SarunasCard** [DockerIt/opencart-docker#10]
Hello,
I have tried to setup project as described in readme with docker-compose.yml:
```
version: '3'
services:
  db:
    image: chrisss404/opencart:2.0.1.0-mysql5.7
    restart: always
    volumes:
      - ./volume-mysql:/var/lib/db-data
    env_file:
      - shop-config.env

  web:
    image: chrisss404/opencart:2.0.1.0-php7.0
    links:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    environment:
      - SHOP_ADMIN_USER=admin
      - SHOP_ADMIN_PASSWORD=password
```
and got errors:
```
web_1  | ERROR: Could not execute the statement: "UPDATE oc_user SET `username`='admin' WHERE `user_id`='1';" Table 'opencart.oc_user' doesn't exist
web_1  | ERROR: Could not execute the statement: "UPDATE oc_user SET `salt`='DHLRdlwFI', `password`='790b1c13fc0369936c4b14252b30173e3b97d842' WHERE `user_id`='1';" Table 'opencart.oc_user' doesn't exist

```
Tried changing images to mysql5.6, mysql5.5; using: `docker-compose up --build`, or `docker-compose up --build --remove-orphans`, or `docker-compose build --no-cache && docker-compose up -d --force-recreate` result the same errors.
Tried get in to mysql container, log in to mysql server: database `opencart` exists but running `use opencart; show tables;` return `Empty set`.
